# Generated by Django 4.2.1 on 2023-05-25 06:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='телефон')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='полное имя')),
                ('photo', models.ImageField(upload_to='', verbose_name='фото')),
                ('work_duration', models.DurationField(verbose_name='стаж работы')),
            ],
            options={
                'verbose_name': 'мастер',
                'verbose_name_plural': 'мастера',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'проффесия',
                'verbose_name_plural': 'проффесии',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('working_time_from', models.TimeField(verbose_name='работает с')),
                ('working_time_to', models.TimeField(verbose_name='работает по')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
            ],
            options={
                'verbose_name': 'салон',
                'verbose_name_plural': 'салоны',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=400, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('master', models.ManyToManyField(related_name='servises', to='beauty.master')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=400, verbose_name='отзыв')),
                ('date', models.DateField(auto_now=True, verbose_name='дата отзыва')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.client', verbose_name='клиент')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='beauty.salon')),
            ],
            options={
                'verbose_name': 'отзыв',
                'verbose_name_plural': 'отзывы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='день')),
                ('time', models.TimeField(verbose_name='время')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.client', verbose_name='клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.service', verbose_name='услуга')),
            ],
            options={
                'verbose_name': 'запись',
                'verbose_name_plural': 'записи',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beauty.profession', verbose_name='проффесия'),
        ),
    ]
