# Generated by Django 4.2.1 on 2023-05-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'verbose_name': 'профессия', 'verbose_name_plural': 'профессии'},
        ),
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='картинка'),
        ),
    ]
