# Generated by Django 4.2.1 on 2023-05-28 22:52

from django.db import migrations
from datetime import time
from assets.db import salons, masters, services


def migrate_salons(apps, schema_editor):
    Salon = apps.get_model('beauty', 'Salon')
    
    for salon_data in salons:
        Salon.objects.create(
            name=salon_data['name'],
            address=salon_data['address'],
            working_time_from=time(9, 0),  # Устанавливаем время открытия 9:00
            working_time_to=time(21, 0)  # Устанавливаем время закрытия 21:00
        )


def migrate_masters(apps, schema_editor):
    Master = apps.get_model('beauty', 'Master')
    Profession = apps.get_model('beauty', 'Profession')

    for master_data in masters:
        profession, _ = Profession.objects.get_or_create(name=master_data['profession'])
        Master.objects.create(
                fullname=master_data['fullname'],
                profession=profession
            )


def migrate_services(apps, schema_editor):
    CategoryService = apps.get_model('beauty', 'CategoryService')
    Service = apps.get_model('beauty', 'Service')
    for category_data in services:
        name = category_data['name']
        category, _ = CategoryService.objects.get_or_create(name=name)
        for service_data in category_data['services']:
            Service.objects.create(
                name=service_data['name'],
                price=int(service_data['price'].replace(' ', '')),
                # image=service_data['image'],
                category=category
            )


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate_salons),
        migrations.RunPython(migrate_masters),
        migrations.RunPython(migrate_services),
    ]
