# Generated by Django 4.2.1 on 2023-05-29 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_auto_20230529_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='beauty.master', verbose_name='мастер'),
        ),
    ]
