# Generated by Django 4.2.1 on 2023-05-28 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0002_categoryservice_alter_profession_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(upload_to='media', verbose_name='фото'),
        ),
    ]
