# Generated by Django 4.2.1 on 2023-05-27 23:53

from django.db import migrations
from assets.db import masters

from os.path import join
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent.parent.parent


def migrate_masters(apps, schema_editor):
    Master = apps.get_model('beauty', 'Master')
    Profession = apps.get_model('beauty', 'Profession')

    for master_data in masters:
        profession, _ = Profession.objects.get_or_create(name=master_data['profession'])
        Master.objects.create(
                fullname=master_data['fullname'],
                profession=profession
            )


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0004_alter_master_photo_alter_master_work_duration_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_masters)
    ]
