# Generated by Django 4.2.1 on 2023-05-28 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0005_auto_20230528_1142'),
    ]

    operations = [
    ]
