# Generated by Django 4.2.1 on 2023-05-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='work_duration',
            field=models.IntegerField(verbose_name='стаж работы'),
        ),
    ]
