# Generated by Django 4.2.1 on 2023-05-28 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0006_auto_20230528_1147'),
        ('beauty', '0009_alter_order_master'),
    ]

    operations = [
    ]
