# Generated by Django 4.2.1 on 2023-05-28 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0010_merge_0006_auto_20230528_1147_0009_alter_order_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Категория', to='beauty.categoryservice'),
        ),
        migrations.AlterField(
            model_name='master',
            name='photo',
            field=models.ImageField(upload_to='masters', verbose_name='фото'),
        ),
        migrations.AlterField(
            model_name='master',
            name='work_duration',
            field=models.IntegerField(blank=True, null=True, verbose_name='стаж работы (лет)'),
        ),
        migrations.AlterField(
            model_name='salon',
            name='image',
            field=models.ImageField(upload_to='salons', verbose_name='картинка'),
        ),
    ]
