# Generated by Django 4.2.1 on 2023-05-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0011_service_category_alter_master_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services', verbose_name='картинка'),
        ),
    ]
