# Generated by Django 4.2.1 on 2023-05-28 11:37

from django.db import migrations
from assets.db import services


def migrate_services(apps, schema_editor):
    CategoryService = apps.get_model('beauty', 'CategoryService')
    Service = apps.get_model('beauty', 'Service')
    for category_data in services:
        name = category_data['name']
        category, _ = CategoryService.objects.get_or_create(name=name)
        for service_data in category_data['services']:
            Service.objects.create(
                name=service_data['name'],
                price=int(service_data['price'].replace(' ', '')),
                # image=service_data['image'],
                category=category
            )


class Migration(migrations.Migration):

    dependencies = [
        ('beauty', '0012_alter_service_image'),
    ]

    operations = [
        migrations.RunPython(migrate_services)
    ]
